dist: xenial
language: python

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install 'pytest>=4.6' pytest-cov codecov flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install mock; fi

script:
  - pytest --cov=webssh
  - flake8
  
after_success:
  - codecov

jobs:
  include:
    - stage: deploy
        script:
          - docker build -t webssh:build .
        deploy:
          - provider: script
            script: |
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              docker tag webssh:build docker.io/jammyhewitt/webssh:latest
              docker push docker.io/jammyhewitt/webssh:latest
            on:
              branch: master
          - provider: script
            script: |
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              docker tag webssh:$TRAVIS_TAG docker.io/jammyhewitt/webssh:$TRAVIS_TAG
              docker push docker.io/jammyhewitt/webssh:$TRAVIS_TAG
            on:
              tags: true
